import { IsString, IsNotEmpty, IsArray, ValidateNested } from 'class-validator';
import { Type } from 'class-transformer';
import { ApiProperty } from '@nestjs/swagger';

export class FileContentDto {
  @ApiProperty({ description: 'File path', example: 'src/App.jsx' })
  @IsString()
  @IsNotEmpty()
  path: string;

  @ApiProperty({ description: 'File content' })
  @IsString()
  @IsNotEmpty()
  content: string;
}

export class PushFilesDto {
  @ApiProperty({
    description: 'Repository name',
    example: 'my-awesome-app',
  })
  @IsString()
  @IsNotEmpty()
  repository: string;

  @ApiProperty({
    description: 'Commit message',
    example: 'Initial commit: Generated by Jarvis AI',
  })
  @IsString()
  @IsNotEmpty()
  message: string;

  @ApiProperty({
    description: 'Branch name',
    example: 'main',
    default: 'main',
  })
  @IsString()
  @IsNotEmpty()
  branch?: string;

  @ApiProperty({
    description: 'Array of files to push',
    type: [FileContentDto],
  })
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => FileContentDto)
  files: FileContentDto[];
}
